from django.urls import path
from .views import (
    admin_index,
    users_list,
    user_create,
    user_edit,
    user_delete,
    user_toggle_active,
    user_password,
    roles_list,
    role_create,
    backup_list,
    backup_create,
    backup_restore,
    backup_schedule,
    access_matrix,
    data_check,
    admin_analytics,
    admin_analytics_export,
    entity_list,
    entity_detail,
    entity_create,
    entity_edit,
    entity_delete,
)

urlpatterns = [
    path("", admin_index, name="admin-index"),
    path("users/", users_list, name="admin-users"),
    path("users/create/", user_create, name="admin-user-create"),
    path("users/<int:pk>/edit/", user_edit, name="admin-user-edit"),
    path("users/<int:pk>/delete/", user_delete, name="admin-user-delete"),
    path("users/<int:pk>/toggle/", user_toggle_active, name="admin-user-toggle"),
    path("users/<int:pk>/password/", user_password, name="admin-user-password"),
    path("roles/", roles_list, name="admin-roles"),
    path("roles/create/", role_create, name="admin-role-create"),
    path("backups/", backup_list, name="admin-backups"),
    path("backups/create/", backup_create, name="admin-backup-create"),
    path("backups/<int:pk>/restore/", backup_restore, name="admin-backup-restore"),
    path("backups/schedule/", backup_schedule, name="admin-backup-schedule"),
    path("access/", access_matrix, name="admin-access"),
    path("data-check/", data_check, name="admin-data-check"),
    path("analytics/", admin_analytics, name="admin-analytics"),
    path("analytics/export/", admin_analytics_export, name="admin-analytics-export"),
    path("entities/<slug:slug>/", entity_list, name="admin-entity-list"),
    path("entities/<slug:slug>/create/", entity_create, name="admin-entity-create"),
    path("entities/<slug:slug>/<int:pk>/", entity_detail, name="admin-entity-detail"),
    path("entities/<slug:slug>/<int:pk>/edit/", entity_edit, name="admin-entity-edit"),
    path("entities/<slug:slug>/<int:pk>/delete/", entity_delete, name="admin-entity-delete"),
]
